"""initial_schema

Revision ID: 2c3e01842923
Revises: 
Create Date: 2026-09-26 02:41:41.132392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c3e01842923'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schemes',
    sa.Column('scheme_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=64), nullable=False),
    sa.Column('ministry', sa.String(length=255), nullable=True),
    sa.Column('scope', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('scheme_id')
    )
    op.create_index(op.f('ix_schemes_niche'), 'schemes', ['niche'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_external_reference'), 'users', ['external_reference'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('goal', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('candidate_schemes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_table('agent_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('selected_field', sa.String(length=64), nullable=True),
    sa.Column('state_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_events_case_id'), 'agent_events', ['case_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('scheme_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'scheme_id', name='uq_case_scheme_application')
    )
    op.create_index(op.f('ix_applications_case_id'), 'applications', ['case_id'], unique=False)
    op.create_index(op.f('ix_applications_scheme_id'), 'applications', ['scheme_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('human_confirmations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('confirmation_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('proposed_changes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_patch', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_confirmations_case_id'), 'human_confirmations', ['case_id'], unique=False)
    op.create_index(op.f('ix_human_confirmations_status'), 'human_confirmations', ['status'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('profile_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_case_id'), 'profiles', ['case_id'], unique=True)
    op.create_index(op.f('ix_profiles_profile_fingerprint'), 'profiles', ['profile_fingerprint'], unique=False)
    op.create_table('application_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_events_application_id'), 'application_events', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_events_event_type'), 'application_events', ['event_type'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('file_reference', sa.String(length=255), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_application_id'), 'documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_table('scheme_evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=True),
    sa.Column('scheme_id', sa.String(length=64), nullable=False),
    sa.Column('profile_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rules_version', sa.String(length=32), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_evaluations_application_id'), 'scheme_evaluations', ['application_id'], unique=False)
    op.create_index(op.f('ix_scheme_evaluations_case_id'), 'scheme_evaluations', ['case_id'], unique=False)
    op.create_index(op.f('ix_scheme_evaluations_is_stale'), 'scheme_evaluations', ['is_stale'], unique=False)
    op.create_index(op.f('ix_scheme_evaluations_outcome'), 'scheme_evaluations', ['outcome'], unique=False)
    op.create_index(op.f('ix_scheme_evaluations_profile_fingerprint'), 'scheme_evaluations', ['profile_fingerprint'], unique=False)
    op.create_index(op.f('ix_scheme_evaluations_scheme_id'), 'scheme_evaluations', ['scheme_id'], unique=False)
    op.create_table('document_discrepancies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('profile_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_discrepancies_document_id'), 'document_discrepancies', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_discrepancies_field_name'), 'document_discrepancies', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_discrepancies_field_name'), table_name='document_discrepancies')
    op.drop_index(op.f('ix_document_discrepancies_document_id'), table_name='document_discrepancies')
    op.drop_table('document_discrepancies')
    op.drop_index(op.f('ix_scheme_evaluations_scheme_id'), table_name='scheme_evaluations')
    op.drop_index(op.f('ix_scheme_evaluations_profile_fingerprint'), table_name='scheme_evaluations')
    op.drop_index(op.f('ix_scheme_evaluations_outcome'), table_name='scheme_evaluations')
    op.drop_index(op.f('ix_scheme_evaluations_is_stale'), table_name='scheme_evaluations')
    op.drop_index(op.f('ix_scheme_evaluations_case_id'), table_name='scheme_evaluations')
    op.drop_index(op.f('ix_scheme_evaluations_application_id'), table_name='scheme_evaluations')
    op.drop_table('scheme_evaluations')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_application_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_application_events_event_type'), table_name='application_events')
    op.drop_index(op.f('ix_application_events_application_id'), table_name='application_events')
    op.drop_table('application_events')
    op.drop_index(op.f('ix_profiles_profile_fingerprint'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_case_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_human_confirmations_status'), table_name='human_confirmations')
    op.drop_index(op.f('ix_human_confirmations_case_id'), table_name='human_confirmations')
    op.drop_table('human_confirmations')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_scheme_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_case_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_agent_events_case_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_users_external_reference'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_schemes_niche'), table_name='schemes')
    op.drop_table('schemes')
    # ### end Alembic commands ###
